### ISSUE TITLE
No serial output when code compiled in Arduino IDE 

### ISSUE THREAD

**Issue by stilsota** [Every-Flavor-Robotics/motorgo-arduino#1] opened 2024-01-11 22:17 UTC
Mac installation - Sonoma 14.2 
Arduino 2.2.1 

Reference "Spin 2 Motors" example. When compiled and uploaded in Platformio, board writes to serial terminal in VSCode and Arduino. When compiled in Arduino, board writes to neither Arudino nor VSCode serial terminal. 

Troubleshooting steps tried: 
- replacing USB cable 
- replacing board (issue repeated on 2 MotorGo V1rev2 boards)
- simplifying code (only serial.begin in setup and println in loop) - same issue 
- view in screen in terminal. same issue. no serial output observed when compiled in Arduino. 
- changing baud rate. did not work for 115200 or 9600.

**Comment by SwapnilPande** [comment] 2024-01-12 03:31
Thanks for the detailed bug report, I was able to reproduce the bug. I believe the issue is that `USB_CDC_ON_BOOT` is disabled in the microcontroller settings. The serial output seems to work as expected when this is enabled.

**Comment by SwapnilPande** [comment] 2024-01-12 03:45
I've created a branch that enables USB CDC on Boot by default. Can you test this branch to see if this fixes the issue.

Uninstall the motorgo boards from Arduino from the boards manager. In the `Additional Board Managers URLS`, paste the following URL instead: `https://raw.githubusercontent.com/Every-Flavor-Robotics/motorgo-arduino/bug-1/enable-usb-cdc/board_definitions/package_motorgo_index.json`

Re-install the MotorGo boards and try flashing code again.

**Comment by SwapnilPande** [comment] 2024-02-08 20:27
Closed by #4

**Closed as completed by SwapnilPande** 2024-02-08 20:27 UTC
